# Créez ici votre docker compose

# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=AfterDB
    networks:
      after:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      after:

  afterpublic:
    container_name: public
    build:
      context: django-site/
      dockerfile: ./Dockerfile.front
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=AfterDB
      - SHARD=public
    depends_on:
      - db
    networks:
      after:

  afterapi:
    container_name: api
    build:
      context: django-site/
      dockerfile: ./Dockerfile.api
    ports:
      - 8001:8000
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=AfterDB
      - SHARD=api
    depends_on:
      - db
    networks:
      after:

networks:
   after:


