# Generated by Django 5.1 on 2024-09-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_rename_plat_ritz_plats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ritz',
            old_name='plats',
            new_name='plat',
        ),
    ]
